### ISSUE TITLE
为什么使用/imagine生成图片后，/change请求却是“关联任务不允许执行变化”

### ISSUE THREAD

**Issue by iischajn** [novicezk/midjourney-proxy#104]
是我理解错了吗，生成图片之后，通过U和V来进行变化重新提交任务是个正常操作吧。

<img width="449" alt="image" src="https://github.com/novicezk/midjourney-proxy/assets/3065129/5ca4ca8e-bd29-457b-b7a3-d4c232041098">

代码这里我不太理解，只允许自上传的图片允许变化么。

```
if (Set.of(TaskAction.IMAGINE, TaskAction.VARIATION).contains(targetTask.getAction())) {
			return SubmitResultVO.fail(ReturnCode.VALIDATION_ERROR, "关联任务不允许执行变化=>"+targetTask.getAction());
		}
```

**Comment by novicezk** [comment]
是个bug，2.1.1版本已修复
