### ISSUE TITLE
生成的api能返回出Result，但是我想1-4操作，比如说U1或者V1他就报错了

### ISSUE THREAD

**Issue by Sanyela** [novicezk/midjourney-proxy#11]
![image](https://user-images.githubusercontent.com/119792728/235098787-745ffa62-1715-40ec-a283-e15d5ba1e7cb.png)
是请求的路径的问题么

**Comment by Sanyela** [comment]
![image](https://user-images.githubusercontent.com/119792728/235099329-2b981b55-141e-4275-b88f-0c6114a370b4.png)
submit-uv也是一样    都是这个错误

**Comment by novicezk** [comment]
@Sanyela 可能是docker镜像的代码不是最新的，我之后更新下，或者也可以先拉java代码方式启动

**Comment by Sanyela** [comment]
更新了通知一下哟

**Comment by novicezk** [comment]
@Sanyela 更新了镜像，1.1版本
