### ISSUE TITLE
上传图片到discord失败

### ISSUE THREAD

**Issue by Git-HandClup** [novicezk/midjourney-proxy#114]

**Comment by Git-HandClup** [comment]
![image](https://github.com/novicezk/midjourney-proxy/assets/38003767/b25e852e-0795-420a-ac27-6e5531d24235)
报错如图，通过浏览器直接访问base64是能够正常显示图片

**Comment by Fred3343** [comment]
2023-06-07 15:43:03.434 ERROR 1 --- [    TaskQueue-3] c.g.n.m.service.DiscordServiceImpl       : 上传图片到discord失败
我也遇到了相同的问题
@novicezk

**Comment by Fred3343** [comment]
token确实会发生变化，但是我这边核对过了，guild，channel，user-token，bot-token都是正确的，还是出现上传图片到discord失败的情况
@Git-HandClup

**Comment by Git-HandClup** [comment]
好吧，艾特一下大佬解答一下 @novicezk

**Comment by Fred3343** [comment]
我把所有的操作重新做了一遍，已正常了哈
@Git-HandClup @novicezk 感谢感谢
