### ISSUE TITLE
推送任务变更失败, 任务ID: 0689775962942554, 描述: 404 Not Found: "room not found"

### ISSUE THREAD

**Issue by echoy189** [novicezk/midjourney-proxy#118]
大佬。运行一段时间之后，推送任务变更失败 是怎么回事
![irn3QCpGoM](https://github.com/novicezk/midjourney-proxy/assets/44562617/1c391ab7-1bac-4d38-8cb7-5fed63c1c803)

**Comment by novicezk** [comment]
检查wechat端接口问题，可能群组被删除了，或者群组没有命名
