### ISSUE TITLE
请求接口trigger/submit报错

### ISSUE THREAD

**Issue by moyuvip** [novicezk/midjourney-proxy#12]
Resolved [org.springframework.http.converter.HttpMessageNotReadableException: JSON parse error: Unexpected character ('/' (code 47)): maybe a (non-standard) comment? (not recognized as one since Feature 'ALLOW_COMMENTS' not enabled for parser); nested exception is com.fasterxml.jackson.core.JsonParseException: Unexpected character ('/' (code 47)): maybe a (non-standard) comment? (not recognized as one since Feature 'ALLOW_COMMENTS' not enabled for parser)<EOL> at [Source: (org.springframework.util.StreamUtils$NonClosingInputStream); line: 2, column: 6]]

![image](https://user-images.githubusercontent.com/129498752/235299345-0a42e4ac-1057-41d1-92f9-dfd198a48a91.png)

**Comment by novicezk** [comment]
提交的json参数是什么样的

**Comment by moyuvip** [comment]
> 提交的json参数是什么样的

		headers.add("user-agent", "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.99 Safari/537.36");
加一行这个就行了
