### ISSUE TITLE
403 Forbidden: \"error code: 1010\

### ISSUE THREAD

**Issue by moyuvip** [novicezk/midjourney-proxy#13]
![image](https://user-images.githubusercontent.com/129498752/235300348-7ccc1d5f-ab41-49ac-b0d7-f09f1378f680.png)

**Comment by 21z0s3** [comment]
在postJson方法中添加了一行
`headers.add("user-agent", "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.99 Safari/537.36");`
问题就解决了

**Comment by novicezk** [comment]
感谢提出，我改下代码

**Comment by moyuvip** [comment]
> 在postJson方法中添加了一行 `headers.add("user-agent", "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.99 Safari/537.36");` 问题就解决了

感谢
