### ISSUE TITLE
任务队列脏任务阻塞

### ISSUE THREAD

**Issue by HumorChen** [novicezk/midjourney-proxy#139]
跑几个小时之后里面就有脏任务阻塞了并发，状态一直是SUBMITTED,但是没有发出去，也没有变更状态，也没有被超时掉，应该要有一个定时任务来检测这种脏任务，不然并发几个，有几个脏任务就堵住了用不了

**Comment by novicezk** [comment]
使用的哪个版本

**Comment by HumorChen** [comment]
2.1.6

**Comment by novicezk** [comment]
新版本已修复
