### ISSUE TITLE
机器人成功怎么回调没看懂

### ISSUE THREAD

**Issue by moyuvip** [novicezk/midjourney-proxy#14]

**Comment by novicezk** [comment]
@moyuvip 设置mj.notify-hook，任务变更后可以推送到这个地址

**Comment by moyuvip** [comment]
明白了，用websocket和前端连接吗，然后把回调的数据推过去

**Comment by moyuvip** [comment]
> @moyuvip 设置mj.notify-hook，任务变更后可以推送到这个地址


这个我明白了
