### ISSUE TITLE
线程池bug

### ISSUE THREAD

**Issue by HumorChen** [novicezk/midjourney-proxy#147]
![image](https://github.com/novicezk/midjourney-proxy/assets/46368749/ed413bbb-e746-4198-889f-78cd2cf42845)
如果我队列填的1000个，那岂不是等待线程核心就有1000个线程要开，这个截图里标出的位置应该要填并发数，因为等待超时的线程池的个数是由并发的线程调起的，因此应该直接等于并发线程数。
第二点
![image](https://github.com/novicezk/midjourney-proxy/assets/46368749/52919da7-194f-4ced-a39a-8b910cc728f7)
如果等待线程异常进入第二个catch，那这个任务就一直卡死在那了，不会超时出去了，就会一直占用一个并发线程。

**Comment by novicezk** [comment]
好的，我验证下，感谢反馈
