### ISSUE TITLE
V操作时任务失败

### ISSUE THREAD

**Issue by lbritney** [novicezk/midjourney-proxy#150]
<img width="881" alt="image" src="https://github.com/novicezk/midjourney-proxy/assets/250510/b3dbb26b-8773-4e3d-afd5-7e8e00f0ac77">
<img width="1468" alt="image" src="https://github.com/novicezk/midjourney-proxy/assets/250510/a5cbc9c0-7d52-4330-bfdd-d9c4f8684149">
请问怎么调整？

**Comment by lbritney** [comment]
生图，和 U任务都正常，只有V时，日志显示超时

**Comment by novicezk** [comment]
频道中关掉remix模式

**Comment by lbritney** [comment]
感谢~ @novicezk
