### ISSUE TITLE
队列阻塞

### ISSUE THREAD

**Issue by Dooy** [novicezk/midjourney-proxy#153]
就输入一个 set 失败了 但是一直藏在队列中

<img width="523" alt="image" src="https://github.com/novicezk/midjourney-proxy/assets/3765401/ebba630f-74f8-4fe5-bc19-90a26a12f691">

**Comment by novicezk** [comment]
使用最新2.2.2版本试试

**Comment by Dooy** [comment]
收到谢谢，其实 2.2.1 你已经解决。

感谢及时更新
