### ISSUE TITLE
绘图变化VARIATION（V）的时候没有触发机器人直到任务超时

### ISSUE THREAD

**Issue by zhylio** [novicezk/midjourney-proxy#165]
在DISCORD频道看到V按钮已经点亮，但是没有触发，点击V的时候都是提示如下图
![image](https://github.com/novicezk/midjourney-proxy/assets/26716602/5445f142-b34e-471f-a27d-85f4dcbb5b0c)

**Comment by AlcoholTobaccoCode** [comment]
<img width="725" alt="image" src="https://github.com/novicezk/midjourney-proxy/assets/49547938/f1d7f310-84f3-41bc-936b-86c0baadad58">
把这个关掉

**Comment by zhylio** [comment]
但是，又遇到一个问题，就是触发了V，频道绘画成功了，任务没回调直至超时

**Comment by zhylio** [comment]
哦不对，是接收到了，但是过程没状态，只有结束才有
