### ISSUE TITLE
submit v 目前代码的请求是拉起一个弹框，需要再发起一次请求，后一次请求 id 参数如何获取啊

### ISSUE THREAD

**Issue by JSNU-Bighead** [novicezk/midjourney-proxy#17]
![image](https://user-images.githubusercontent.com/21335228/236179943-c3cd4922-3a1e-4d13-b508-f0ada81ad138.png)

**Comment by novicezk** [comment]
暂不支持remix模式

**Comment by JSNU-Bighead** [comment]
thx
