### ISSUE TITLE
50035，"code": "INTERACTION_APPLICATION_COMMAND_INVALID_VERSION"

### ISSUE THREAD

**Issue by akahoo** [novicezk/midjourney-proxy#186]
{"code": 50035, "errors": {"data": {"_errors": [{"code": "INTERACTION_APPLICATION_COMMAND_INVALID_VERSION", "message": "\u8be5\u6743\u9650\u5df2\u8fc7\u65f6\uff0c\u8bf7\u7a0d\u5019\u51e0\u5206\u949f\u518d\u8bd5"}]}}, "message": "Invalid Form Body"}

这个错误大家有遇到过吗

**Comment by fk5431** [comment]
我也是这个，请问怎么解决啊

**Comment by akahoo** [comment]
把api-params/imagine.json文件中的version修改成 "version": "1118961510123847772"
