### ISSUE TITLE
图生图的模式，一直显示任务超时

### ISSUE THREAD

**Issue by shundao-haihe** [novicezk/midjourney-proxy#212]
{"action":"IMAGINE","id":"3714863075843529","prompt":"http://xjp.ltyc.top/img/1687918395719_mmexport1687828240581.jpg A girl, business attire --v 5 --s 250 --ar 1:1 --iw 1","promptEn":"http://xjp.ltyc.top/img/1687918395719_mmexport1687828240581.jpg A girl, business attire --v 5 --s 250 --ar 1:1 --iw 1","description":"/imagine http://xjp.ltyc.top/img/1687918395719_mmexport1687828240581.jpg A girl, business attire --v 5 --s 250 --ar 1:1 --iw 1","state":null,"submitTime":1687918434046,"startTime":1687918434065,"finishTime":1687918745088,"imageUrl":null,"status":"FAILURE","progress":"","failReason":"任务超时"}

**Comment by novicezk** [comment]
同问题 #204
