### ISSUE TITLE
/error problem. 

### ISSUE THREAD

**Issue by joyhope** [novicezk/midjourney-proxy#29]
Whitelabel Error Page
This application has no explicit mapping for /error, so you are seeing this as a fallback.

Mon May 08 12:55:23 CST 2023
There was an unexpected error (type=Method Not Allowed, status=405).

**Comment by novicezk** [comment]
请使用 post json请求submit接口，可以用postman之类的工具

**Comment by joyhope** [comment]
Thanks.  我理解错了. 

{"code":10003,"description":"Unknown Channel","result":null}   这个是说明 配置channel 有问题是吧?

**Comment by joyhope** [comment]
My mistake.  It works. thanks.
