### ISSUE TITLE
实现原理（持续更新）

### ISSUE THREAD

**Issue by inewlife** [novicezk/midjourney-proxy#320]
1.如何实现弹窗逻辑
public Message<Void> remix(Task task, String messageId, int index, String messageHash, int messageFlags, String nonce, String prompt) {
		variation(task,messageId,index,messageHash,messageFlags,nonce);
		log.debug("[midjouney-proxy-starter] > 等待返回remix组件id");
		while (StringUtil.isNullOrEmpty(task.getComponentId())) {
			synchronized (task) {
				try {
					task.wait();
				} catch (InterruptedException e) {
					e.printStackTrace();
				}
			}
		}
		log.debug("[midjouney-proxy-starter] > remix组件id为 {} ",task.getComponentId());
		log.debug("[midjouney-proxy-starter] > 调用remix操作");
		String newOnce = SnowFlake.INSTANCE.nextId();
		task.setProperty(Constants.TASK_PROPERTY_NONCE, newOnce);
		if (prompt==null){
			prompt=task.getPrompt();
		}
		task.setPrompt(prompt);
		task.setPromptEn(prompt);
		log.debug("[midjouney-proxy-starter] > newOnce为 {}",newOnce);
		String paramsStr = replaceInteractionParams(this.modalParamsJson, newOnce)
				.replace("$message_hash", messageHash)
				.replace("$index", String.valueOf(index))
				.replace("$component_id", task.getComponentId())
				.replace("$prompt", prompt);

		Message<Void> result = postJsonAndCheckStatus(paramsStr);
		return result;
	}

2.如何实现局部重绘
public Message<Void> inpaint(Task task, String messageId,  String messageHash, int messageFlags, String nonce, String prompt, String mask) {
		String custom_id = "MJ::Inpaint::1::$message_hash::SOLO".replace("$message_hash",messageHash);
		common(messageId,custom_id,messageFlags,nonce);
		log.debug("[midjouney-proxy-starter] > 等待返回iframe组件id");
		while (StringUtil.isNullOrEmpty(task.getComponentId())) {
			synchronized (task) {
				try {
					task.wait();
				} catch (InterruptedException e) {
					e.printStackTrace();
				}
			}
		}
		log.debug("[midjouney-proxy-starter] > iframe组件id为 {} ",task.getComponentId());
		log.debug("[midjouney-proxy-starter] > 调用iframe操作");
		String newOnce = SnowFlake.INSTANCE.nextId();
		task.setProperty(Constants.TASK_PROPERTY_NONCE, newOnce);
		task.setAction(TaskAction.VARIATION);
		if (prompt==null){
			prompt=task.getPrompt();
		}
		task.setPrompt(prompt);
		task.setPromptEn(prompt);
		task.setProperty(Constants.TASK_PROPERTY_FINAL_PROMPT, prompt);
		log.debug("[midjouney-proxy-starter] > newOnce为 {}",newOnce);
		String new_custom_id = task.getComponentId().replace("MJ::iframe::","");
		String paramsStr = replaceInteractionParams(this.jobParamsJson, newOnce)
				.replace("$custom_id", new_custom_id)
				.replace("$mask", mask)
				.replace("$prompt", prompt);

		Message<Void> result = postJobJsonAndCheckStatus(paramsStr);
		return result;
	}

	public Message<Void> common(String messageId,String custom_id, int messageFlags, String nonce) {
		String paramsStr = replaceInteractionParams(this.commonParamsJson, nonce)
				.replace("$message_id",messageId)
				.replace("$custom_id", custom_id);

		paramsStr = new JSONObject(paramsStr).put("message_flags", messageFlags).toString();
		return postJsonAndCheckStatus(paramsStr);
	}

**Comment by inewlife** [comment]
`package com.github.novicezk.midjourney.wss.handle;

import cn.hutool.core.text.CharSequenceUtil;
import com.github.novicezk.midjourney.Constants;
import com.github.novicezk.midjourney.enums.MessageType;
import com.github.novicezk.midjourney.enums.TaskAction;
import com.github.novicezk.midjourney.enums.TaskStatus;
import com.github.novicezk.midjourney.result.Message;
import com.github.novicezk.midjourney.support.Task;
import com.github.novicezk.midjourney.support.TaskCondition;
import com.github.novicezk.midjourney.util.ContentParseData;
import com.github.novicezk.midjourney.util.ConvertUtils;
import com.github.novicezk.midjourney.util.UVContentParseData;
import lombok.extern.slf4j.Slf4j;
import net.dv8tion.jda.api.utils.data.DataObject;
import org.springframework.stereotype.Component;

import java.util.Set;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

/**
 * variation消息处理.
 * 完成(create): **cat** - Variations (Strong或Subtle) by <@1012983546824114217> (relaxed)
 * 完成(create): **cat** - Variations by <@1012983546824114217> (relaxed)
 */
@Slf4j
@Component
public class VariationSuccessHandler extends MessageHandler {
	private static final String START_CONTENT_REGEX = "Making variations for image #(\\d) with prompt \\*\\*(.*?)\\*\\* - <@\\d+> \\((.*?)\\)";
	private static final String OLD_CONTENT_REGEX = "\\*\\*(.*?)\\*\\* - Variations by <@\\d+> \\((.*?)\\)";
	private static final String CONTENT_REGEX = "\\*\\*(.*?)\\*\\* - Variations \\(.*?\\) by <@\\d+> \\((.*?)\\)";
//	private static final String CONTENT_REGEX_INPANT = "\\*\\*regionNonce: \\d+, (.*?)\\*\\* - Variations \\(.*?\\) by <@\\d+> \\((.*?)\\)";
	private static final String REGEX_INPANT_START = "\\*\\*regionNonce: \\d+, (.*?)\\*\\* - <@\\d+> \\((.*?)\\)";
	private static final String CONTENT_REGEX_INPAINT = "\\*\\*regionNonce:\\s(\\d+?),\\s";
	private static final String CONTENT_REGEX_INPAINT_v2 = "regionNonce:\\s\\d+?,\\s(.*+)";

	public String getInpaintNonce(String content,String reg){
		Matcher matcher = Pattern.compile(reg).matcher(content);
		if (!matcher.find()) {
			return null;
		}
		return matcher.group(1);
	}

	@Override
	public void handle(MessageType messageType, DataObject message) {
		String content = getMessageContent(message);
		if (MessageType.CREATE.equals(messageType)) {
			UVContentParseData start = parseStart(content);
			if (start != null) {
				Task task;
				// 开始
				if (message.hasKey("nonce")){
					 task = this.taskQueueHelper.getRunningTaskByNonce(message.getString("nonce"));
				}else {
					String newNonce = getInpaintNonce(content,CONTENT_REGEX_INPAINT);
					if (newNonce!=null){
						 task = this.taskQueueHelper.getRunningTaskByNonce(newNonce);
						 if (task!=null){
							 log.debug("from message_reference.message_id {}",message.getObject("message_reference").getString("message_id"));
						 }

							// message.getObject("message_reference").getString("message_id")
					}else {
						return;
					}
				}
				if (task == null) {
					return;
				}
				log.debug("from message_id {}",message.getString("id"));
				task.setProperty(Constants.TASK_PROPERTY_PROGRESS_MESSAGE_ID, message.getString("id"));
				task.setStatus(TaskStatus.IN_PROGRESS);
				task.awake();
				return;
			}
			UVContentParseData end = parse(content);
			if (end == null) {
				return;
			}
			TaskCondition condition = new TaskCondition()
					.setFinalPromptEn(end.getPrompt())
					.setActionSet(Set.of(TaskAction.VARIATION))
					.setStatusSet(Set.of(TaskStatus.SUBMITTED, TaskStatus.IN_PROGRESS));
			findAndFinishImageTask(condition, end.getPrompt(), message);
			String afterRePrompt = getInpaintNonce(end.getPrompt(),CONTENT_REGEX_INPAINT_v2);
			if (afterRePrompt!=null){
				condition = new TaskCondition()
						.setFinalPromptEn(afterRePrompt)
						.setActionSet(Set.of(TaskAction.VARIATION))
						.setStatusSet(Set.of(TaskStatus.SUBMITTED, TaskStatus.IN_PROGRESS));
				findAndFinishImageTask(condition, afterRePrompt, message);
			}
			
		} else if (MessageType.UPDATE == messageType) {
			UVContentParseData parseData = parse(content);
			if (parseData == null || CharSequenceUtil.equalsAny(parseData.getStatus(), "relaxed", "fast")) {
				return;
			}
			log.debug("message_id {}",message.getString("id"));
			TaskCondition condition = new TaskCondition()
					.setProgressMessageId(message.getString("id"))
					.setActionSet(Set.of(TaskAction.VARIATION))
					.setStatusSet(Set.of(TaskStatus.SUBMITTED, TaskStatus.IN_PROGRESS));
			Task task = this.taskQueueHelper.findRunningTask(condition)
					.findFirst().orElse(null);
			if (task == null) {
				return;
			}
			task.setProperty(Constants.TASK_PROPERTY_PROGRESS_MESSAGE_ID, message.getString("id"));
			task.setStatus(TaskStatus.IN_PROGRESS);
			task.setProgress(parseData.getStatus());
			task.setImageUrl(getImageUrl(message));
			task.awake();
		} else if (MessageType.INTERACTION_SUCCESS.equals(messageType)){
			// remix开启时获取组件id
			String componentId = message.getString("id");
			String nonce = message.getString("nonce");
			log.debug("remix {}",message);
			Task task = taskQueueHelper.getRunningTaskByNonce(nonce);
			if (null!=task && !task.getAction().equals(TaskAction.INPAINT)){
				task.setComponentId(componentId);
			}
		}
	}



	private UVContentParseData parseStart(String content) {
		Matcher matcher = Pattern.compile(START_CONTENT_REGEX).matcher(content);
		if (!matcher.find()) {
			matcher = Pattern.compile(REGEX_INPANT_START).matcher(content);
			if (matcher.find()){
				UVContentParseData parseData = new UVContentParseData();

				parseData.setPrompt(matcher.group(1));

				return parseData;
			}
			return null;
		}
		UVContentParseData parseData = new UVContentParseData();
		parseData.setIndex(Integer.parseInt(matcher.group(1)));
		parseData.setPrompt(matcher.group(2));
		parseData.setStatus(matcher.group(3));
		return parseData;
	}

	private UVContentParseData parse(String content) {
		UVContentParseData data = parse(content, CONTENT_REGEX);
		if (data == null) {
			return parse(content, OLD_CONTENT_REGEX);
		}
		return data;
	}

	private static UVContentParseData parse(String content, String regex) {
		Matcher matcher = Pattern.compile(regex).matcher(content);
		if (!matcher.find()) {
			return null;
		}
		UVContentParseData parseData = new UVContentParseData();
		parseData.setPrompt(matcher.group(1));
		parseData.setStatus(matcher.group(2));
		return parseData;
	}
}
`

**Comment by dongdong-gogogo** [comment]
感谢大佬

**Comment by inewlife** [comment]
接收不到弹窗消息的原理：https://github.com/LaiBaoYuan/midjourney-sdk/issues/1#event-10305025185

**Comment by inewlife** [comment]
有什么不知道实现的功能都可以在这里讨论，这个作者太坑了，搞了个收费版阉割功能

**Comment by dongdong-gogogo** [comment]
> 有什么不知道实现的功能都可以在这里讨论，这个作者太坑了，搞了个收费版阉割功能

毕竟人家靠技术吃饭的呀

**Comment by novicezk** [comment]
@inewlife 你觉得有好的实现，可以自己fork出来开发分享，吃水骂挖井人的操作我无法理解。希望能互相尊重
