### ISSUE TITLE
/task/list problem 

### ISSUE THREAD

**Issue by joyhope** [novicezk/midjourney-proxy#34]
curl http://xxx/task/list

<!doctype html><html lang="en"><head><title>HTTP Status 404 – Not Found</title><style type="text/css">body {font-family:Tahoma,Arial,sans-serif;} h1, h2, h3, b {color:white;background-color:#525D76;} h1 {font-size:22px;} h2 {font-size:16px;} h3 {font-size:14px;} p {font-size:12px;} a {color:black;} .line {height:1px;background-color:#525D76;border:none;}</style></head><body><h1>HTTP Status 404 – Not Found</h1></body></html>

我执行过任务，成功显示出来。但是没查询到，是什么原因。

**Comment by novicezk** [comment]
curl http://xxx/mj/task/list 少了/mj

**Comment by joyhope** [comment]
加了/mj/ 404 没有了, 但是没列出任务. 任务应该缓存1天吗?

**Comment by joyhope** [comment]
比较快做了测试, 数据都有了. 估计缓冲是系统决定的.
