### ISSUE TITLE
When I query http://ip:port/mj/task/list according to the tutorial, the status is always "NOT-START"?

### ISSUE THREAD

**Issue by Bruce337f** [novicezk/midjourney-proxy#39]
{
        "action": "IMAGINE",
        "state": "test:22",
        "submitTime": 1683624936564,
        "finishTime": null,
        "imageUrl": null,
        "status": "NOT_START"
    }

**Comment by novicezk** [comment]
检查频道中自己新建的机器人是否在线，绘图是否完成
