### ISSUE TITLE
redis keys * 认真的吗

### ISSUE THREAD

**Issue by hitonya** [novicezk/midjourney-proxy#40]
Set<String> keys = this.redisTemplate.keys(getRedisKey("*"));

**Comment by novicezk** [comment]
getRedisKey方法中加了mj-task::前缀

**Comment by hitonya** [comment]
keys 查找跟有无前缀无关啊， 加了前缀还不是一样需要遍历所有key，量上来redis就费了

**Comment by novicezk** [comment]
redis可能不是个最佳方式，需要根据条件查询task，提供了TaskService接口和mj.task-store.type配置，后续增加rdbms实现。如果redis有好的方案，欢迎提供或提交pr
