### ISSUE TITLE
docker启动不成功

### ISSUE THREAD

**Issue by teg1c** [novicezk/midjourney-proxy#5]
不太熟悉 java 
看 `./build-image.sh` 的逻辑好像是需要jar包？

**Comment by novicezk** [comment]
需要先mvn package打jar包，后面我把jar包直接放上来吧

**Comment by novicezk** [comment]
@teg1c 镜像已上传到dockerhub,  https://hub.docker.com/r/novicezk/midjourney-proxy

**Comment by teg1c** [comment]
> @teg1c 镜像已上传到dockerhub, https://hub.docker.com/r/novicezk/midjourney-proxy

好的，感谢。
