### ISSUE TITLE
docker成功运行，但是请求api的时候显示HTTP Status 404 – Not Found

### ISSUE THREAD

**Issue by Sanyela** [novicezk/midjourney-proxy#7]
![image](https://user-images.githubusercontent.com/119792728/235053099-adb6fd47-9772-4314-a98f-69d307a517a1.png)

**Comment by Sanyela** [comment]
解决了，默认路径是http://IP/mj/trigger/submit

**Comment by novicezk** [comment]
好的，我在快速启动步骤中加下说明
