### ISSUE TITLE
关于 net.dv8tion.jda.api.exceptions.ErrorResponseException: -1: java.net.SocketTimeoutException

### ISSUE THREAD

**Issue by yuepenglei** [novicezk/midjourney-proxy#72]
先说背景：windows 10 电脑，代码下载到本地，idea 运行，报错如下图：
![微信图片_20230518133413](https://github.com/novicezk/midjourney-proxy/assets/23113933/5f51fff3-29e6-4663-b7d4-76dd995c0748)

链接超时，与 Discord 建立链接超时。

首先 vpn 没有问题，开了全局代理，浏览器可以正常访问 youtube 网站，用 postman 也可以访问 youtube 网站。

跟朋友交流时，了解到一个信息，windows 用梯子的全局代理的时候，不是真正的全局代理，对于 jvm 发起的网络请求，不是经过梯子转发。mac 电脑上使用梯子开了全局代理后是真正的全局代理。

于是找了两个朋友验证一下：A 朋友 mac 电脑，用我的梯子工具，代码能运行起来。 B 朋友 mac 电脑，用他自己的梯子工具，代码能运行起来。

之后开始研究在 windows 电脑开了 vpn 全局代理的情况下，如何让本地运行的 java 程序可以访问外网。
1：修改代码，使用代理【由于我的节点都是 Trojan协议，java 代码好像是不支持这个协议的代理，所以没搞定】
2：修改 idea 的代理，但是 idea 的代理只是作用于 idea ，比如下载插件的时候可以通过代理下载，对运行的 java 程序是没效果的。

最终，还会没能解决这个问题，希望别的同学，有用 windows 电脑在本地拉去代码后 idea 中运行起来这个项目的人，分享一下经验。

**Comment by tiny-gao** [comment]
启动的时候加上代理，具体的代理host和port可以在windows搜索下“代理服务器”里头可以看到代理IP地址和端口。启动加上vm参数，如下：
java -Dhttp.proxyHost=127.0.0.1 -Dhttp.proxyPort=7890 \
-Dhttps.proxyHost=127.0.0.1 -Dhttps.proxyPort=7890 \
-DsocksProxyHost=127.0.0.1 -DsocksProxyPort=7890 \

**Comment by yuepenglei** [comment]
> 启动的时候加上代理，具体的代理host和port可以在windows搜索下“代理服务器”里头可以看到代理IP地址和端口。启动加上vm参数，如我的代理是本机，端口是7890，则jvm启动时候配置vm如下： -Dhttp.proxyHost=127.0.0.1 -Dhttp.proxyPort=7890 -Dhttps.proxyHost=127.0.0.1 -Dhttps.proxyPort=7890 -DsocksProxyHost=127.0.0.1 -DsocksProxyPort=7890

有用，确实解决了问题，不过我的还要再设置一下 设置一下websocket的代理 才可以

**Comment by yuepenglei** [comment]
目前问题已解决，更新下记录：
1：设置 jvm 启动参数 
-Dhttps.proxyHost=127.0.0.1 -Dhttps.proxyPort=21882 
这个是你的梯子代理的 ip 和端口，可以在梯子的系统设置或者别的设置里面找到。

解决了这个报错：
![image](https://github.com/novicezk/midjourney-proxy/assets/23113933/ed28864f-e66f-4a34-bf15-99c97696d2f8)




2：还需要设置一下websocket的代理
![image](https://github.com/novicezk/midjourney-proxy/assets/23113933/a07906ec-de4c-4340-b48e-10490d97708b)

解决了这个报错：
![image](https://github.com/novicezk/midjourney-proxy/assets/23113933/b6917709-b47a-46a8-8bf1-77b2335ac20e)

**Comment by tiny-gao** [comment]
> 目前问题已解决，更新下记录： 1：设置 jvm 启动参数 -Dhttps.proxyHost=127.0.0.1 -Dhttps.proxyPort=21882 这个是你的梯子代理的 ip 和端口，可以在梯子的系统设置或者别的设置里面找到。
> 
> 解决了这个报错： ![image](https://user-images.githubusercontent.com/23113933/239503626-ed28864f-e66f-4a34-bf15-99c97696d2f8.png)
> 
> 2：还需要设置一下websocket的代理 ![image](https://user-images.githubusercontent.com/23113933/239502033-a07906ec-de4c-4340-b48e-10490d97708b.png)
> 
> 解决了这个报错： ![image](https://user-images.githubusercontent.com/23113933/239503140-b6917709-b47a-46a8-8bf1-77b2335ac20e.png)

其实你的代理支持sock模式，只要配置：DsocksProxyHost=127.0.0.1 -DsocksProxyPort=XXXX ，不需要在代码中写。
