### ISSUE TITLE
关于midjourney在微信上的调用

### ISSUE THREAD

**Issue by Git-HandClup** [novicezk/midjourney-proxy#73]
做了个插件在微信上调用midjourney-proxy，中文翻译未配置，具体效果如图。
![1684397081348](https://github.com/novicezk/midjourney-proxy/assets/38003767/d39cf2a1-f64c-4356-a1bb-14a11d613f5c)

**Comment by Fred3343** [comment]
elif context.type == ContextType.IMAGE_CREATE:
            ok, retstring = self.create_img(query, 0)
            @Git-HandClup 这两行应该怎么修改呢？求救大佬

**Comment by Git-HandClup** [comment]
@Fred3343 create_img是调用了openai的画图，但我没用，我是将mj弄成了插件的方式接入的

**Comment by Fred3343** [comment]
@Git-HandClup 大佬是怎么实现的？求教求教

**Comment by Git-HandClup** [comment]
mj插件：[https://github.com/Git-HandClup/plugin_midjourney](https://github.com/Git-HandClup/plugin_midjourney)
