### ISSUE TITLE
提示没有权限

### ISSUE THREAD

**Issue by good2luck** [novicezk/midjourney-proxy#8]
![image](https://user-images.githubusercontent.com/13247094/235058650-ec4b9a10-aaec-44e1-872f-bfb15cade78a.png)
按步骤配置好，请求后提示没有权限。是因为用户token不对吗？

**Comment by good2luck** [comment]
已解决，请求时增加一个user-agent header即可

**Comment by novicezk** [comment]
> 已解决，请求时增加一个user-agent header即可

@good2luck postman里加user-agent，还是改了java代码？

**Comment by good2luck** [comment]
改了代码，在top.xudj.service.impl.DiscordServiceImpl#postJson方法中，headers.set("User-Agent", {user-agent});

**Comment by good2luck** [comment]
@novicezk
