### ISSUE TITLE
可以整个交流群吗？

### ISSUE THREAD

**Issue by good2luck** [novicezk/midjourney-proxy#9]

**Comment by zhitaozeng** [comment]
![50042c8c886fe5b60a343723fdc8f60](https://user-images.githubusercontent.com/44150257/235340714-441ac2fc-dfd7-40fe-8f84-07aabfcd1ef9.jpg)

进群一起讨论一下

**Comment by GitWingSky** [comment]
更新下新码呗~

**Comment by gitxiaodi** [comment]
> 更新下新码呗~

同求一个群二维码

**Comment by novicezk** [comment]
扫主页的二维码 @GitWingSky @gitxiaodi 
![image](https://github.com/novicezk/midjourney-proxy/assets/20700387/ede0d35e-b636-495b-a9af-6658e938ad65)

**Comment by lironghuiGithub** [comment]
群满了只能通过成员邀请进群了18550588278，哪位大哥邀请我一下

**Comment by novicezk** [comment]
@lironghuiGithub 首页放了2群的码，可以扫这个
