### ISSUE TITLE
敏感词误判

### ISSUE THREAD

**Issue by LOVECHEN** [novicezk/midjourney-proxy#98]
`As I gaze into the sky, I spot a colossal, transparent balloon floating in the air. Inside it, a beautiful girl gracefully hovers, seemingly suspended in time.  ` 这个语句 不知道哪里有敏感词

**Comment by cnjxxf** [comment]
如何【规范使用】midjourney-proxy的屏蔽关键字配置文件

在linux目录先建个配置文件目录
比如我之前创建过的midjourney-proxy-docker目录
/root/soft/midjourney-proxy-docker/config
可以根据自定义一个目录，也可以参考我的目录
mkidr -p /root/soft/midjourney-proxy-docker/config

第一步：创建配置文件
touch application.yml
根据自己的配置参数编辑该文件内容：使用nano application.yml命令，编辑后cat该文件内容如下
root@showsky:~/soft/midjourney-proxy-docker/config# cat application.yml 
server:
port: 8080
servlet:
context-path: /mj
logging:
level:
ROOT: info
com.github.novicezk.midjourney: debug
knife4j:
enable: true
openapi:
title: Midjourney Proxy API文档
description: 代理 MidJourney 的discord频道，实现api形式调用AI绘图
concat: novicezk
url: https://github.com/novicezk/midjourney-proxy
version: v1.6.1
terms-of-service-url: https://github.com/novicezk/midjourney-proxy
group:
api:
group-name: API
api-rule: package
api-rule-resources:
- com.github.novicezk.midjourney.controller
mj:
discord:
guild-id: XXXXXX
channel-id: XXXXXX
user-token: XXXXXX
bot-token: XXXXXX
task-store:
type: in_memory
timeout: 30d
translate-way: baidu
queue:
timeout-minutes: 5
core-size: 3
queue-size: 10
root@showsky:~/soft/midjourney-proxy-docker/config# 
第二步：创建空白替换文件（这样就不屏蔽任何字符，当然这样存在风险，自己把握）
touch banned-words.txt
第三步：创建启动文件
touch midjourney-proxy-docker-1.6.1.sh

使用nano midjourney-proxy-docker-1.6.1.sh先行编辑
root@showsky:~/soft/midjourney-proxy-docker# cat midjourney-proxy-docker-1.6.1.sh 
#文件内容如下
docker run -d --name midjourney-proxy-1.6.1-20230526 \
-p 8086:8080 \
-v /root/soft/midjourney-proxy-docker/config:/home/spring/config \
-e mj.translate-way=baidu \
-e mj.baidu-translate.appid=20230501XXX \
-e mj.baidu-translate.app-secret=BaiduXXXXXX \
--restart=always \
novicezk/midjourney-proxy:1.6.1
root@showsky:~/soft/midjourney-proxy-docker# 
第四步：修改getmj.php中的mj aip接口参数
测试效果。

**Comment by LOVECHEN** [comment]
> 如何【规范使用】midjourney-proxy的屏蔽关键字配置文件
> 
> 在linux目录先建个配置文件目录 比如我之前创建过的midjourney-proxy-docker目录 /root/soft/midjourney-proxy-docker/config 可以根据自定义一个目录，也可以参考我的目录 mkidr -p /root/soft/midjourney-proxy-docker/config
> 
> 第一步：创建配置文件 touch application.yml 根据自己的配置参数编辑该文件内容：使用nano application.yml命令，编辑后cat该文件内容如下 root@showsky:~/soft/midjourney-proxy-docker/config# cat application.yml server: port: 8080 servlet: context-path: /mj logging: level: ROOT: info com.github.novicezk.midjourney: debug knife4j: enable: true openapi: title: Midjourney Proxy API文档 description: 代理 MidJourney 的discord频道，实现api形式调用AI绘图 concat: novicezk url: https://github.com/novicezk/midjourney-proxy version: v1.6.1 terms-of-service-url: https://github.com/novicezk/midjourney-proxy group: api: group-name: API api-rule: package api-rule-resources:
> 
> * com.github.novicezk.midjourney.controller
>   mj:
>   discord:
>   guild-id: XXXXXX
>   channel-id: XXXXXX
>   user-token: XXXXXX
>   bot-token: XXXXXX
>   task-store:
>   type: in_memory
>   timeout: 30d
>   translate-way: baidu
>   queue:
>   timeout-minutes: 5
>   core-size: 3
>   queue-size: 10
>   root@showsky:~/soft/midjourney-proxy-docker/config#
>   第二步：创建空白替换文件（这样就不屏蔽任何字符，当然这样存在风险，自己把握）
>   touch banned-words.txt
>   第三步：创建启动文件
>   touch midjourney-proxy-docker-1.6.1.sh
> 
> 使用nano midjourney-proxy-docker-1.6.1.sh先行编辑 root@showsky:~/soft/midjourney-proxy-docker# cat midjourney-proxy-docker-1.6.1.sh #文件内容如下 docker run -d --name midjourney-proxy-1.6.1-20230526 -p 8086:8080 -v /root/soft/midjourney-proxy-docker/config:/home/spring/config -e mj.translate-way=baidu -e mj.baidu-translate.appid=20230501XXX -e mj.baidu-translate.app-secret=BaiduXXXXXX --restart=always novicezk/midjourney-proxy:1.6.1 root@showsky:~/soft/midjourney-proxy-docker# 第四步：修改getmj.php中的mj aip接口参数 测试效果。

我的配置没问题 ，我的意思是我不知道触发他的哪个敏感词，使用的是官方的banned_words

**Comment by novicezk** [comment]
transparent 应该是这个。可以验证下，如果确实不会触发mj异常，可以删除它

**Comment by LOVECHEN** [comment]
谢谢我试试
